server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    # 1. 修改驱动类名（MySQL 8.0+ 必须使用 cj 包）
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 2. 建议将时区改为上海，避免 Java 时间与数据库时间差 8 小时
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    # 3. Spring Boot 3.x 中 redis 配置层级移动到了 spring.data.redis
    redis:
      host: 192.168.106.129
      port: 6379
      password: 123456
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null

mybatis-plus:
  type-aliases-package: com.hmdp.entity
  # 4. 建议显式配置下划线转驼峰（Spring Boot 3 默认通常开启，但写上更稳）
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.hmdp: debug
    dev.langchain4j: debug

langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      model-name: qwen3.6-plus
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      model-name: qwen3.6-plus
      log-requests: true
      log-responses: true
    embedding-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      model-name: text-embedding-v3
      log-requests: true
      log-responses: true
      max-segments-per-batch: 10 # 平台限制，每次给模型传输最多10个片段
  community:
    redis:
      host: localhost
      port: 6379

