## ????? (MySQL 8.0+ ???? com.mysql.cj.jdbc.Driver)
#jdbc.driver=com.mysql.cj.jdbc.Driver
#
## ????? URL
## ???????? (serverTimezone) ?????? (useUnicode & characterEncoding) ??????????
#jdbc.url=jdbc:mysql://localhost:3306/ssm_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#
## ??????
#jdbc.username=root
#
## ?????
#jdbc.password=123456
# JDBC????
jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/ssm_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
jdbc.username=root
jdbc.password=123456