# Redis 配置

# 日志配置
logging:
  level:
    root: INFO
    com.itheima: DEBUG
spring:
  data:
    redis:
      host: 192.168.106.129
      port: 6379
      password: 123456
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
