package org.omg.PortableServer;


/**
* org/omg/PortableServer/LIFESPAN_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/8-2-build-windows-x64-cygwin-sans-NAS/jdk8u471/2292/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Friday, September 26, 2025 5:09:14 AM UTC
*/

public interface LIFESPAN_POLICY_ID
{

  /**
	 * The value representing LIFESPAN_POLICY_ID.
	 */
  public static final int value = (int)(17L);
}
